name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # Install the Android SDK and components
      - name: Install Android SDK
        run: |
          # Create the android-sdk directory
          mkdir -p $HOME/android-sdk/cmdline-tools

          # Download and extract command line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk/cmdline-tools/

          # Move the extracted tools to the expected location
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest

          # Set up environment variables
          echo "##[add-path]$HOME/android-sdk/cmdline-tools/latest/bin"
          echo "##[add-path]$HOME/android-sdk/platform-tools"

          # Accept licenses
          yes | sdkmanager --licenses

          # Install required SDK components
          sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;31.0.0"

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Optionally, upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
